// @ts-nocheck
// Type checking disabled due to version differences in lucide-react icons
// Missing icons will fallback to default at runtime

import React from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  BookOpen,
  Server,
  Database,
  Cloud,
  Shield,
  Lock,
  Key,
  Globe,
  Network,
  CreditCard,
  Wallet,
  Banknote,
  Coins,
  Receipt,
  Bell,
  Mail,
  MessageSquare,
  Send,
  HardDrive,
  Cpu,
  Layers,
  GitBranch,
  Workflow,
  User,
  Users,
  UserCheck,
  CheckCircle,
  AlertTriangle,
  AlertCircle,
  Zap,
  Activity,
  Box,
  Package,
  Settings,
  Cog,
  Search,
  Eye,
  FileText,
  File,
  Folder,
  Download,
  Upload,
  RefreshCw,
  RotateCw,
  ArrowRight,
  ArrowLeftRight,
  Link,
  Unlink,
  Wifi,
  WifiOff,
  Monitor,
  Smartphone,
  Tablet,
  Terminal,
  Code,
  Braces,
  Hash,
  AtSign,
  Clock,
  Timer,
  Calendar,
  BarChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  DollarSign,
  ShoppingCart,
  Store,
  Tag,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  MessageCircle,
  Phone,
  Video,
  Image,
  Camera,
  Mic,
  Volume2,
  Play,
  Pause,
  Shuffle,
  Repeat,
  Filter,
  Sliders,
  ToggleLeft,
  Power,
  Battery,
  Plug,
  Radio,
  Rss,
  Share2,
  GitMerge,
  GitPullRequest,
  Container,
  Blocks,
  // Additional commonly used icons
  Copy,
  LifeBuoy,
  Car,
  Target,
  XCircle,
  X,
  Check,
  Plus,
  Minus,
  Home,
  Building,
  Building2,
  Factory,
  Warehouse,
  Rocket,
  Plane,
  Ship,
  Train,
  Truck,
  Bike,
  Navigation,
  Map,
  MapPin,
  Compass,
  Crosshair,
  Focus,
  Lightbulb,
  Flame,
  Droplet,
  Wind,
  Sun,
  Moon,
  CloudRain,
  Snowflake,
  Umbrella,
  Leaf,
  TreeDeciduous,
  Flower2,
  Bug,
  Anchor,
  Award,
  Trophy,
  Medal,
  Crown,
  Gem,
  Gift,
  Cake,
  Coffee,
  Pizza,
  Apple,
  Utensils,
  Wine,
  Beer,
  Scissors,
  Wrench,
  Hammer,
  Screwdriver,
  Paintbrush,
  Palette,
  Pen,
  Pencil,
  Eraser,
  Ruler,
  Calculator,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  FileCode,
  FileJson,
  FileSpreadsheet,
  Files,
  FolderOpen,
  FolderPlus,
  Archive,
  Trash,
  Trash2,
  Save,
  Edit,
  Edit2,
  Edit3,
  Type,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  List,
  ListOrdered,
  CheckSquare,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
  Bookmark,
  Flag,
  Pin,
  Paperclip,
  ExternalLink,
  CornerUpRight,
  CornerDownRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  Move,
  Maximize,
  Minimize,
  Expand,
  Shrink,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  Undo,
  Redo,
  History,
  Rewind,
  FastForward,
  SkipBack,
  SkipForward,
  VolumeX,
  Volume1,
  Headphones,
  Speaker,
  Music,
  Music2,
  Radio as RadioIcon,
  Tv,
  Projector,
  Gamepad2,
  Dices,
  Puzzle,
  Brain,
  Glasses,
  Scan,
  QrCode,
  Barcode,
  Fingerprint,
  ScanFace,
  ShieldCheck,
  ShieldAlert,
  ShieldOff,
  LockOpen,
  Unlock,
  KeyRound,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserX,
  Users2,
  Contact,
  BookUser,
  BadgeCheck,
  BadgeAlert,
  BadgeX,
  CircleDot,
  CircleCheck,
  CircleX,
  CircleAlert,
  CircleHelp,
  CirclePlay,
  CirclePause,
  CircleStop,
  Info,
  HelpCircle,
  AlertOctagon,
  Ban,
  Slash,
  Construction,
  TrafficCone,
  Siren,
  AlarmClock,
  Bell as BellIcon,
  BellRing,
  BellOff,
  Megaphone,
  Inbox,
  MailOpen,
  MailCheck,
  MailX,
  AtSign as AtSignIcon,
  Webhook,
  Api,
  Plug2,
  Cable,
  Usb,
  Bluetooth,
  Signal,
  SignalHigh,
  SignalLow,
  SignalZero,
  Satellite,
  SatelliteDish,
  Router,
  ServerCog,
  ServerCrash,
  ServerOff,
  DatabaseBackup,
  HardDriveDownload,
  HardDriveUpload,
  CloudUpload,
  CloudDownload,
  CloudOff,
  CloudCog,
  FolderCloud,
  FileUp,
  FileDown,
  FileCheck,
  FileX,
  FilePlus,
  FileMinus,
  FileSearch,
  FileWarning,
  Sparkles,
  Sparkle,
  Wand,
  Wand2,
  Magic,
  PartyPopper,
  Confetti,
  Ticket,
  Tags,
  Receipt as ReceiptIcon,
  CreditCard as CreditCardIcon,
  Landmark,
  PiggyBank,
  HandCoins,
  CircleDollarSign,
  BadgeDollarSign,
  Percent,
  Calculator as CalculatorIcon,
  Scale,
  Gavel,
  BookCheck,
  BookX,
  BookMarked,
  Library,
  GraduationCap,
  School,
  Presentation,
  ChartBar,
  ChartLine,
  ChartPie,
  ChartArea,
  ChartScatter,
  Gauge,
  Timer as TimerIcon,
  Hourglass,
  Watch,
  Stopwatch,
  CalendarDays,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  CalendarClock,
  Milestone,
  Goal,
  Target as TargetIcon,
  Crosshair as CrosshairIcon,
  Radar,
  Binary,
  Regex,
  Variable,
  Function,
  Component,
  Boxes,
  Puzzle as PuzzleIcon,
  LayoutGrid,
  LayoutList,
  LayoutDashboard,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Columns,
  Rows,
  Table,
  Table2,
  Grid,
  Kanban,
  Trello,
  Workflow as WorkflowIcon,
  Network as NetworkIcon,
  Share,
  Share2 as Share2Icon,
  Forward,
  Reply,
  ReplyAll,
  CornerUpLeft,
  CornerDownLeft,
  Repeat as RepeatIcon,
  Repeat1,
  Infinity,
  Hash as HashIcon,
  Asterisk,
  Command,
  Option,
  Delete,
  Backspace,
  Space,
  CornerLeftUp,
  CornerRightUp,
  MoveUp,
  MoveDown,
  MoveLeft,
  MoveRight,
  Grip,
  GripVertical,
  GripHorizontal,
  MoreHorizontal,
  MoreVertical,
  Menu,
  PanelLeftOpen,
  PanelRightOpen,
  Sidebar,
  AppWindow,
  Laptop,
  Laptop2,
  ScreenShare,
  Cast,
  Airplay,
  MonitorSmartphone,
  TabletSmartphone,
  Watch as WatchIcon,
  Printer,
  ScanLine,
  Bot,
  BrainCircuit,
  BrainCog,
  Cpu as CpuIcon,
  MemoryStick,
  Microchip,
  CircuitBoard,
  Infinity as InfinityIcon,
  RefreshCcw,
  Loader,
  Loader2,
  LoaderCircle,
  Hourglass as HourglassIcon,
  Clapperboard,
  Film,
  Cctv,
  MonitorPlay,
  ScreenShareOff,
  Webcam,
  Focus as FocusIcon,
  Aperture,
  SunDim,
  SunMedium,
  Sunrise,
  Sunset,
  Cloudy,
  CloudSun,
  CloudMoon,
  Thermometer,
  ThermometerSun,
  ThermometerSnowflake,
  Waves,
  Mountain,
  MountainSnow,
  Trees,
  PalmTree,
  Flower,
  Sprout,
  Vegan,
  Salad,
  Beef,
  Egg,
  Fish,
  IceCream,
  Cookie,
  Croissant,
  Sandwich,
  Soup,
  CupSoda,
  GlassWater,
  Milk,
  Baby,
  PersonStanding,
  Accessibility,
  Footprints,
  Bone,
  Pill,
  Stethoscope,
  Syringe,
  Bandage,
  HeartPulse,
  Dumbbell,
  Tent,
  Campfire,
  FlameKindling,
  Bed,
  BedDouble,
  BedSingle,
  Bath,
  ShowerHead,
  Lamp,
  LampDesk,
  LampFloor,
  LampCeiling,
  Armchair,
  Sofa,
  DoorOpen,
  DoorClosed,
  GalleryVertical,
  GalleryHorizontal,
  Image as ImageIcon,
  ImagePlus,
  ImageMinus,
  ImageOff,
  Frame,
  Stamp,
  Sticker,
  StickyNote,
  NotebookPen,
  NotebookText,
  ClipboardPen,
  ClipboardCopy,
  ClipboardPaste,
  FilePen,
  FileEdit,
  Signature,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  // Infrastructure
  'server': Server,
  'database': Database,
  'cloud': Cloud,
  'shield': Shield,
  'lock': Lock,
  'key': Key,
  'globe': Globe,
  'network': Network,
  'hard-drive': HardDrive,
  'cpu': Cpu,
  'layers': Layers,
  'monitor': Monitor,
  'terminal': Terminal,
  'container': Container,
  'blocks': Blocks,
  'router': Router,
  'server-cog': ServerCog,
  'server-crash': ServerCrash,
  'server-off': ServerOff,
  'database-backup': DatabaseBackup,
  'satellite': Satellite,
  'satellite-dish': SatelliteDish,

  // Payment / Finance
  'credit-card': CreditCard,
  'wallet': Wallet,
  'banknote': Banknote,
  'coins': Coins,
  'receipt': Receipt,
  'dollar-sign': DollarSign,
  'shopping-cart': ShoppingCart,
  'store': Store,
  'tag': Tag,
  'landmark': Landmark,
  'piggy-bank': PiggyBank,
  'hand-coins': HandCoins,
  'circle-dollar-sign': CircleDollarSign,
  'percent': Percent,
  'scale': Scale,

  // Communication
  'bell': Bell,
  'bell-ring': BellRing,
  'bell-off': BellOff,
  'mail': Mail,
  'mail-open': MailOpen,
  'mail-check': MailCheck,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  'send': Send,
  'phone': Phone,
  'radio': Radio,
  'rss': Rss,
  'share': Share2,
  'share2': Share2,
  'megaphone': Megaphone,
  'inbox': Inbox,

  // Data / Dev
  'git-branch': GitBranch,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'workflow': Workflow,
  'code': Code,
  'braces': Braces,
  'hash': Hash,
  'at-sign': AtSign,
  'api': Api,
  'webhook': Webhook,
  'binary': Binary,
  'regex': Regex,
  'variable': Variable,
  'function': Function,
  'component': Component,
  'bot': Bot,
  'brain': Brain,
  'brain-circuit': BrainCircuit,
  'brain-cog': BrainCog,

  // Users
  'user': User,
  'users': Users,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-x': UserX,
  'users2': Users2,
  'contact': Contact,

  // Status & Feedback
  'check-circle': CheckCircle,
  'check': Check,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'alert-octagon': AlertOctagon,
  'zap': Zap,
  'activity': Activity,
  'x-circle': XCircle,
  'x': X,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'circle-alert': CircleAlert,
  'circle-help': CircleHelp,
  'info': Info,
  'help-circle': HelpCircle,
  'ban': Ban,
  'slash': Slash,
  'badge-check': BadgeCheck,
  'badge-alert': BadgeAlert,

  // Objects
  'box': Box,
  'boxes': Boxes,
  'package': Package,
  'settings': Settings,
  'cog': Cog,
  'search': Search,
  'eye': Eye,
  'filter': Filter,
  'sliders': Sliders,
  'target': Target,
  'crosshair': Crosshair,
  'focus': Focus,
  'copy': Copy,
  'clipboard': Clipboard,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,

  // Files
  'book': BookOpen,
  'book-open': BookOpen,
  'file-text': FileText,
  'file': File,
  'file-code': FileCode,
  'file-json': FileJson,
  'folder': Folder,
  'folder-open': FolderOpen,
  'archive': Archive,
  'files': Files,
  'save': Save,

  // Edit & Actions
  'edit': Edit,
  'edit2': Edit2,
  'edit3': Edit3,
  'pen': Pen,
  'pencil': Pencil,
  'eraser': Eraser,
  'trash': Trash,
  'trash2': Trash2,
  'download': Download,
  'upload': Upload,
  'refresh': RefreshCw,
  'refresh-cw': RefreshCw,
  'refresh-ccw': RefreshCcw,
  'rotate': RotateCw,
  'rotate-cw': RotateCw,
  'rotate-ccw': RotateCcw,
  'undo': Undo,
  'redo': Redo,
  'arrow-right': ArrowRight,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left-right': ArrowLeftRight,
  'link': Link,
  'external-link': ExternalLink,
  'unlink': Unlink,
  'shuffle': Shuffle,
  'repeat': Repeat,
  'toggle': ToggleLeft,
  'power': Power,
  'plus': Plus,
  'minus': Minus,

  // Safety & Reliability
  'life-buoy': LifeBuoy,
  'lifebuoy': LifeBuoy,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  'shield-off': ShieldOff,
  'lock-open': LockOpen,
  'unlock': Unlock,
  'key-round': KeyRound,

  // Navigation & Maps
  'home': Home,
  'map': Map,
  'map-pin': MapPin,
  'compass': Compass,
  'navigation': Navigation,

  // Transport
  'car': Car,
  'truck': Truck,
  'plane': Plane,
  'train': Train,
  'ship': Ship,
  'bike': Bike,
  'rocket': Rocket,

  // Buildings
  'building': Building,
  'building2': Building2,
  'factory': Factory,
  'warehouse': Warehouse,

  // Network
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'smartphone': Smartphone,
  'tablet': Tablet,
  'laptop': Laptop,
  'plug': Plug,
  'plug2': Plug2,
  'cable': Cable,
  'battery': Battery,
  'bluetooth': Bluetooth,
  'signal': Signal,
  'signal-high': SignalHigh,
  'signal-low': SignalLow,

  // Time
  'clock': Clock,
  'timer': Timer,
  'stopwatch': Stopwatch,
  'hourglass': Hourglass,
  'watch': Watch,
  'calendar': Calendar,
  'calendar-days': CalendarDays,
  'calendar-check': CalendarCheck,
  'alarm-clock': AlarmClock,
  'history': History,

  // Charts & Data
  'bar-chart': BarChart,
  'chart-bar': BarChart,
  'pie-chart': PieChart,
  'chart-pie': PieChart,
  'chart-line': ChartLine,
  'chart-area': ChartArea,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'gauge': Gauge,

  // Media
  'video': Video,
  'image': Image,
  'camera': Camera,
  'mic': Mic,
  'volume': Volume2,
  'volume2': Volume2,
  'volume1': Volume1,
  'volume-x': VolumeX,
  'play': Play,
  'pause': Pause,
  'rewind': Rewind,
  'fast-forward': FastForward,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'headphones': Headphones,
  'speaker': Speaker,
  'music': Music,
  'film': Film,
  'clapperboard': Clapperboard,

  // Social & Rewards
  'star': Star,
  'heart': Heart,
  'heart-pulse': HeartPulse,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'trophy': Trophy,
  'award': Award,
  'medal': Medal,
  'crown': Crown,
  'gem': Gem,
  'gift': Gift,
  'party-popper': PartyPopper,
  'sparkles': Sparkles,
  'sparkle': Sparkle,

  // Ideas & Creativity
  'lightbulb': Lightbulb,
  'wand': Wand,
  'wand2': Wand2,
  'palette': Palette,
  'paintbrush': Paintbrush,

  // Tools
  'wrench': Wrench,
  'hammer': Hammer,
  'screwdriver': Screwdriver,
  'scissors': Scissors,
  'ruler': Ruler,
  'calculator': Calculator,

  // Nature
  'sun': Sun,
  'moon': Moon,
  'flame': Flame,
  'droplet': Droplet,
  'wind': Wind,
  'cloud-rain': CloudRain,
  'snowflake': Snowflake,
  'leaf': Leaf,
  'tree': TreeDeciduous,
  'flower': Flower2,
  'mountain': Mountain,
  'waves': Waves,

  // Food & Drink
  'coffee': Coffee,
  'pizza': Pizza,
  'apple': Apple,
  'utensils': Utensils,
  'wine': Wine,
  'beer': Beer,
  'cake': Cake,

  // Shapes
  'circle': Circle,
  'square': Square,
  'triangle': Triangle,
  'hexagon': Hexagon,
  'octagon': Octagon,
  'diamond': Diamond,

  // UI Elements
  'menu': Menu,
  'sidebar': Sidebar,
  'layout-grid': LayoutGrid,
  'layout-list': LayoutList,
  'layout-dashboard': LayoutDashboard,
  'table': Table,
  'grid': Grid,
  'kanban': Kanban,
  'columns': Columns,
  'rows': Rows,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'maximize': Maximize,
  'minimize': Minimize,
  'expand': Expand,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,

  // Misc
  'flag': Flag,
  'bookmark': Bookmark,
  'pin': Pin,
  'paperclip': Paperclip,
  'anchor': Anchor,
  'bug': Bug,
  'construction': Construction,
  'siren': Siren,
  'fingerprint': Fingerprint,
  'qr-code': QrCode,
  'scan': Scan,
  'loader': Loader,
  'loader2': Loader2,
  'infinity': Infinity,
  'goal': Goal,
  'milestone': Milestone,
  'puzzle': Puzzle,
  'radar': Radar,

  // Auth
  'log-in': LogIn,
  'log-out': LogOut,
};

/**
 * Render an icon by name. If the name matches a known Lucide icon,
 * renders the SVG component. Otherwise uses a default fallback icon.
 */
export function renderIcon(iconName: string, size: number, color: string): React.ReactNode {
  // Normalize icon name: lowercase, handle common variations
  const normalizedName = iconName?.toLowerCase()?.trim() || '';

  // Try exact match first
  let LucideIcon = ICON_MAP[normalizedName];

  // If not found, try with/without hyphens
  if (!LucideIcon) {
    // Try removing hyphens (e.g., "life-buoy" -> "lifebuoy")
    const noHyphens = normalizedName.replace(/-/g, '');
    LucideIcon = ICON_MAP[noHyphens];
  }

  if (!LucideIcon) {
    // Try adding hyphens between camelCase (e.g., "lifebuoy" -> "life-buoy")
    const withHyphens = normalizedName.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
    LucideIcon = ICON_MAP[withHyphens];
  }

  if (LucideIcon) {
    return <LucideIcon size={size} color={color} strokeWidth={2} />;
  }

  // Check if it looks like an emoji (starts with emoji character or is very short non-alpha)
  const isEmoji = /^[\u{1F300}-\u{1F9FF}]|^[\u{2600}-\u{26FF}]|^[\u{2700}-\u{27BF}]/u.test(iconName);
  if (isEmoji || (iconName.length <= 2 && !/^[a-z-]+$/i.test(iconName))) {
    return <span style={{ fontSize: size * 0.85, lineHeight: 1 }}>{iconName}</span>;
  }

  // Fallback: use Box icon as default instead of showing text
  console.warn(`Unknown icon: "${iconName}", using fallback Box icon`);
  return <Box size={size} color={color} strokeWidth={2} />;
}
